global:
  resolve_timeout: 5m

route:
  receiver: "default"

receivers:
  - name: "default"
    # Example: Slack
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/XXXX/XXXX/XXXX'
    #     channel: '#alerts'
