global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "stage-node"
    static_configs:
      - targets: ["107.191.43.166:9100"]

  - job_name: "prod-node"
    static_configs:
      - targets: ["149.28.239.165:9100"]
