apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - grafana.yaml
  - loki.yaml
  - tempo.yaml
  - irc-relay.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: fishvision
