apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: monitoring-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: grafana.staging.wetfish.net
      - op: replace
        path: /spec/rules/1/host
        value: prometheus.staging.wetfish.net
